// ダミーユーザーデータ（仮ログイン用）
export const dummyUsers = [
  {
    user_id: 1,
    email: "manager@jpt.com",
    name: "山田 花子",
    grade: 1,
    role: "manager",
  },
  {
    user_id: 2,
    email: "member1@jpt.com",
    name: "田中 太郎",
    grade: 1,
    role: "member",
  },
  {
    user_id: 3,
    email: "member2@jpt.com",
    name: "鈴木 次郎",
    grade: 2,
    role: "member",
  },
  {
    user_id: 4,
    email: "member3@jpt.com",
    name: "佐藤 三郎",
    grade: 3,
    role: "member",
  },
  {
    user_id: 5,
    email: "coach@jpt.com",
    name: "伊藤 コーチ",
    grade: null,
    role: "coach",
  },
  {
    user_id: 6,
    email: "director@jpt.com",
    name: "渡辺 監督",
    grade: null,
    role: "director",
  },
];

// ダミー部員一覧データ
export const dummyMembers = [
  {
    user_id: 2,
    name: "田中 太郎",
    grade: 1,
    role: "member",
    status: "active",
  },
  {
    user_id: 3,
    name: "鈴木 次郎",
    grade: 2,
    role: "member",
    status: "active",
  },
  {
    user_id: 4,
    name: "佐藤 三郎",
    grade: 3,
    role: "member",
    status: "active",
  },
];

// ダミー測定記録データ
export const dummyMeasurements = [
  {
    measurement_id: 1,
    user_id: 2,
    name: "田中 太郎",
    grade: 1,
    measurement_date: "2024-10-01",
    sprint_50m: 6.3,
    base_running: 12.5,
    throwing_distance: 64,
    pitch_speed: 118,
    batting_speed: 108,
    swing_speed: 111,
    bench_press: 65,
    squat: 90,
    status: "approved",
  },
  {
    measurement_id: 2,
    user_id: 2,
    name: "田中 太郎",
    grade: 1,
    measurement_date: "2024-12-01",
    sprint_50m: 6.2,
    base_running: 12.3,
    throwing_distance: 66,
    pitch_speed: 120,
    batting_speed: 110,
    swing_speed: 113,
    bench_press: 67,
    squat: 92,
    status: "approved",
  },
  {
    measurement_id: 3,
    user_id: 3,
    name: "鈴木 次郎",
    grade: 2,
    measurement_date: "2024-10-01",
    sprint_50m: 6.5,
    base_running: 12.8,
    throwing_distance: 60,
    pitch_speed: 115,
    batting_speed: 105,
    swing_speed: 108,
    bench_press: 60,
    squat: 85,
    status: "pending_member",
  },
  {
    measurement_id: 4,
    user_id: 4,
    name: "佐藤 三郎",
    grade: 3,
    measurement_date: "2024-10-01",
    sprint_50m: 6.1,
    base_running: 12.1,
    throwing_distance: 70,
    pitch_speed: 125,
    batting_speed: 115,
    swing_speed: 118,
    bench_press: 75,
    squat: 100,
    status: "rejected",
  },
];
