const routes = {
  "login-form": LoginForm,
  "user-header": UserHeader,
  "main-menu": MainMenu,
  "entry-form": EntryForm,
  "past-renrakucho-search": PastRenrakuchoSearch,
  "class-entry-renrakucho": ClassEntryRenrakucho,
  "class-past-renrakucho": ClassPastRenrakucho,
  "submission-status": SubmissionStatus,
  "account-management-menu": AccountManagementMenu,
  "account-form": AccountForm,
  "account-search": AccountSearch,
  "account-search-results": AccountSearchResults,
  "account-update-table": AccountUpdateTable,
  "school-nurse-dashboard": SchoolNurseDashboard,
  "chat-room-list": ChatRoomList,
  "chat-room": ChatRoom,
  "archive-management": ArchiveManagement,
  "yearly-processing-menu": YearlyProcessingMenu,
  "grade-promotion": GradePromotion,
  "graduation-management": GraduationManagement,
  "class-reassignment": ClassReassignment,
};
