version: '3'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql_accounts
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: accounts
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppass
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
