version: '3.8'
services:
  mysql:
    environment:
      MYSQL_CHARSET: utf8mb4
      MYSQL_COLLATION: utf8mb4_unicode_ci
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: accounts
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppass
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    image: mysql:8.0
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
