[tool.ruff]
extend-exclude = [] # チェックから対象のファイルを除外
target-version = "py310"

lint.ignore = [
    "G004", # `logging-f-string` : loggingでf-stringを使いたいので無視する
    "D100", # docstring系は今は無視
    "D101", # docstring系は今は無視
    "D103", # docstring系は今は無視
    "D104", # docstring系は今は無視
    "ANN001", # typehintも今は無視
    "ANN201", # returnのtypehintも今は無視
    "ANN202", # returnのtypehintも今は無視
]

line-length = 120
lint.select = [
    "ALL"
]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.lint.pylint]
max-args = 10
