// ============================================================
// dummyData/index.ts  —  図書館システム モックUI用ダミーデータ
// ============================================================

import type {
  User,
  School,
  Book,
  Loan,
  Reservation,
  InterLibraryRequest,
} from "@/types";
import { calcDueDate } from "@/composables/useLoanStatus";

// ── 学校 ─────────────────────────────────────────────────────

export const dummySchools: School[] = [
  { id: 1, name: "A高校", code: "SCH-A" },
  { id: 2, name: "B高校", code: "SCH-B" },
  { id: 3, name: "C高校", code: "SCH-C" },
  { id: 4, name: "D高校", code: "SCH-D" },
  { id: 5, name: "E高校", code: "SCH-E" },
];

// ── ユーザー ─────────────────────────────────────────────────
// パスワードは全員 'pass1234'（authService.ts 内で照合）

export const dummyUsers: (User & { password: string })[] = [
  {
    id: 1,
    email: "student01@school-a.example.jp",
    password: "pass1234",
    name: "田中 一郎",
    role: "student",
    is_committee: false,
    school_id: 1,
    school_name: "A高校",
    grade: 2,
    class_name: "3組",
    barcode: "STU-0001-A",
  },
  {
    id: 2,
    email: "committee01@school-a.example.jp",
    password: "pass1234",
    name: "鈴木 花子",
    role: "student",
    is_committee: true,
    school_id: 1,
    school_name: "A高校",
    grade: 3,
    class_name: "1組",
    barcode: "STU-0002-A",
  },
  {
    id: 3,
    email: "student02@school-a.example.jp",
    password: "pass1234",
    name: "佐藤 次郎",
    role: "student",
    is_committee: false,
    school_id: 1,
    school_name: "A高校",
    grade: 1,
    class_name: "2組",
    barcode: "STU-0003-A",
  },
  {
    id: 4,
    email: "student03@school-a.example.jp",
    password: "pass1234",
    name: "伊藤 三郎",
    role: "student",
    is_committee: false,
    school_id: 1,
    school_name: "A高校",
    grade: 2,
    class_name: "1組",
    barcode: "STU-0004-A",
  },
  {
    id: 5,
    email: "student04@school-b.example.jp",
    password: "pass1234",
    name: "高橋 四郎",
    role: "student",
    is_committee: false,
    school_id: 2,
    school_name: "B高校",
    grade: 1,
    class_name: "2組",
    barcode: "STU-0001-B",
  },
  {
    id: 6,
    email: "librarian01@school-a.example.jp",
    password: "pass1234",
    name: "山本 司書子",
    role: "librarian",
    is_committee: false,
    school_id: 1,
    school_name: "A高校",
    grade: null,
    class_name: null,
    barcode: null,
  },
  {
    id: 7,
    email: "librarian02@school-b.example.jp",
    password: "pass1234",
    name: "中村 書子",
    role: "librarian",
    is_committee: false,
    school_id: 2,
    school_name: "B高校",
    grade: null,
    class_name: null,
    barcode: null,
  },
  {
    id: 8,
    email: "admin@board.example.jp",
    password: "pass1234",
    name: "小林 管理子",
    role: "admin",
    is_committee: false,
    school_id: null,
    school_name: "教育委員会",
    grade: null,
    class_name: null,
    barcode: null,
  },
];

// ── 資料 ─────────────────────────────────────────────────────

export const dummyBooks: Book[] = [
  {
    id: 1,
    barcode: "BK-000001",
    title: "吾輩は猫である",
    author: "夏目漱石",
    publisher: "岩波書店",
    ndc: "913.6",
    isbn: "978-4-00-310201-9",
    school_id: 1,
    school_name: "A高校",
    status: "available",
    location: "第2書架 3列",
  },
  {
    id: 2,
    barcode: "BK-000002",
    title: "こころ",
    author: "夏目漱石",
    publisher: "岩波書店",
    ndc: "913.6",
    isbn: "978-4-00-310089-3",
    school_id: 1,
    school_name: "A高校",
    status: "loaned",
    location: "第2書架 3列",
  },
  {
    id: 3,
    barcode: "BK-000003",
    title: "プログラミング言語Python",
    author: "David Beazley",
    publisher: "オライリー・ジャパン",
    ndc: "007.64",
    isbn: "978-4-87311-905-4",
    school_id: 3,
    school_name: "C高校",
    status: "available",
    location: "第5書架 1列",
  },
  {
    id: 4,
    barcode: "BK-000004",
    title: "坊っちゃん",
    author: "夏目漱石",
    publisher: "新潮社",
    ndc: "913.6",
    isbn: "978-4-10-101001-3",
    school_id: 2,
    school_name: "B高校",
    status: "reserved",
    location: "第2書架 4列",
  },
  {
    id: 5,
    barcode: "BK-000005",
    title: "SQLアンチパターン",
    author: "Bill Karwin",
    publisher: "オライリー・ジャパン",
    ndc: "007.64",
    isbn: "978-4-87311-589-6",
    school_id: 3,
    school_name: "C高校",
    status: "available",
    location: "第5書架 2列",
  },
  {
    id: 6,
    barcode: "BK-000006",
    title: "ノルウェイの森（上）",
    author: "村上春樹",
    publisher: "講談社",
    ndc: "913.6",
    isbn: "978-4-06-198440-3",
    school_id: 1,
    school_name: "A高校",
    status: "inter_library",
    location: "図書館間貸出棚",
  },
  {
    id: 7,
    barcode: "BK-000007",
    title: "JavaScript: The Good Parts",
    author: "Douglas Crockford",
    publisher: "オライリー・ジャパン",
    ndc: "007.64",
    isbn: "978-4-87311-423-3",
    school_id: 2,
    school_name: "B高校",
    status: "available",
    location: "第5書架 3列",
  },
  {
    id: 8,
    barcode: "BK-000008",
    title: "銀河鉄道の夜",
    author: "宮沢賢治",
    publisher: "新潮社",
    ndc: "913.6",
    isbn: "978-4-10-109305-6",
    school_id: 1,
    school_name: "A高校",
    status: "available",
    location: "第2書架 1列",
  },
];

// ── 貸出 ─────────────────────────────────────────────────────
// user_id: 1（田中）が通常貸出中、user_id: 3（佐藤）が延滞中

export const dummyLoans: Loan[] = [
  {
    id: 1,
    book_id: 2,
    book_title: "こころ",
    book_barcode: "BK-000002",
    user_id: 1,
    user_name: "田中 一郎",
    loaned_at: "2026-04-01T10:00:00Z",
    due_date: calcDueDate("2026-04-01T10:00:00Z"),
    returned_at: null,
    is_overdue: false,
  },
  {
    id: 2,
    book_id: 8,
    book_title: "銀河鉄道の夜",
    book_barcode: "BK-000008",
    user_id: 1,
    user_name: "田中 一郎",
    loaned_at: "2026-04-05T10:00:00Z",
    due_date: calcDueDate("2026-04-05T10:00:00Z"),
    returned_at: null,
    is_overdue: false,
  },
  {
    // 延滞中のテストデータ
    id: 3,
    book_id: 7,
    book_title: "JavaScript: The Good Parts",
    book_barcode: "BK-000007",
    user_id: 3,
    user_name: "佐藤 次郎",
    loaned_at: "2026-03-01T10:00:00Z",
    due_date: calcDueDate("2026-03-01T10:00:00Z"),
    returned_at: null,
    is_overdue: true,
  },
];

// ── 予約 ─────────────────────────────────────────────────────

export const dummyReservations: Reservation[] = [
  {
    // 準備完了（受取待ち）
    id: 1,
    book_id: 4,
    book_title: "坊っちゃん",
    book_barcode: "BK-000004",
    user_id: 1,
    user_name: "田中 一郎",
    status: "ready",
    queue_position: null,
    reserved_at: "2026-04-08T10:00:00Z",
    ready_at: "2026-04-09T10:00:00Z",
    expires_at: "2026-04-16T10:00:00Z",
  },
  {
    // 順番待ち
    id: 2,
    book_id: 6,
    book_title: "ノルウェイの森（上）",
    book_barcode: "BK-000006",
    user_id: 1,
    user_name: "田中 一郎",
    status: "waiting",
    queue_position: 2,
    reserved_at: "2026-04-10T10:00:00Z",
    ready_at: null,
    expires_at: null,
  },
];

// ── 図書館間貸出 ──────────────────────────────────────────────

export const dummyInterLibraryRequests: InterLibraryRequest[] = [
  {
    id: 1,
    book_id: 3,
    book_title: "プログラミング言語Python",
    book_barcode: "BK-000003",
    from_school_id: 3,
    from_school_name: "C高校",
    to_school_id: 1,
    to_school_name: "A高校",
    user_id: 1,
    user_name: "田中 一郎",
    status: "shipped",
    requested_at: "2026-04-04T10:00:00Z",
    shipped_at: "2026-04-07T10:00:00Z",
    arrived_at: null,
  },
  {
    id: 2,
    book_id: 5,
    book_title: "SQLアンチパターン",
    book_barcode: "BK-000005",
    from_school_id: 3,
    from_school_name: "C高校",
    to_school_id: 1,
    to_school_name: "A高校",
    user_id: 2,
    user_name: "鈴木 花子",
    status: "pending",
    requested_at: "2026-04-10T10:00:00Z",
    shipped_at: null,
    arrived_at: null,
  },
];
